ktor:
  application:
    modules:
      - jp.simplespace.ApplicationKt.module
  deployment:
    port: 8080

db:
  url: ${DB_URL}
  user: ${DB_USER}
  password: ${DB_PASSWORD}

discord:
  token: ${DISCORD_TOKEN}
  owner_id: ${DISCORD_OWNER_ID}

rvc_api:
  base_url: ${RVC_API_BASE_URL}

switchbot:
  mac_address: ${SWITCHBOT_MAC_ADDRESS}